export const OPENAI_API_KEY_SECRET_NAME = "OPENAI_API_KEY";
export const OPENAI_MODEL_PARAMETER_NAME = "OPENAI_MODEL";
export const DEFAULT_OPENAI_MODEL = "gpt-5.6-luna";
export const OPENAI_REQUEST_TIMEOUT_MS = 30000;
export const OPENAI_RESPOND_MAX_OUTPUT_TOKENS = 1600;
export const OPENAI_SUMMARY_MAX_OUTPUT_TOKENS = 800;
